import type { Metadata } from "next";
import TopBar from "@/components/TopBar/TopBar";
import SideBar from "@/components/SideBar/SideBar";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dux",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopBar />
        <SideBar />
        {children}
      </body>
    </html>
  );
}
